services:
  # ----------------- WEB SERVER (80, 443) ----------------- #

  nginx:
    container_name: nginx
    build:
      context: ./frontend/nginx
      args:
        - HOST_NAME=${HOST_NAME-localhost}
    ports:
      - "8443:443"
    networks:
      - public-net
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  # --------------------- WEB PAGE (80) -------------------- #

  web:
    container_name: web
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/web/src:/app/src
      - ./frontend/web/public:/app/public
    networks:
      - public-net
    restart: unless-stopped

  # --------------------- REDIS (6379) --------------------- #

  redis:
    container_name: redis
    image: redis:7.4.2
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - service-net
    restart: unless-stopped

  # --------------- MICRO-SERVICES --------------- #

  # Node para OAuth (4000)
  node-oauth:
    container_name: node-oauth
    build:
      context: ./backend/services/node/node-oauth
      dockerfile: Dockerfile
    volumes:
      - ./backend/services/node/node-oauth:/src
      - node-oauth_data:/app/data
      - sqlite-login_data:/data # Para SQLite
    environment:
      - GCLIENT_ID=${GCLIENT_ID}
      - PROJECT_ID=${PROJECT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - RDIR_URI=${RDIR_URI}
      - OAUTH_PORT=${OAUTH_PORT}
    ports:
      - "${OAUTH_PORT}:${OAUTH_PORT}"
    depends_on:
      redis:
        condition: service_healthy
      sqlite-login:
        condition: service_started
    networks:
      - public-net
      - service-net
    restart: unless-stopped

  # Node para el juego (4002)
  node-game:
    container_name: node-game
    build:
      context: ./backend/services/node/node-game
      dockerfile: Dockerfile
    volumes:
      - ./backend/services/node/node-game:/src
      - node-game_data:/app/data
    environment:
      - ${GAME_PORT}=${GAME_PORT}
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - public-net
      - service-net
    restart: unless-stopped

  # SQLite para login de usuarios (4003)
  sqlite-login:
    container_name: sqlite-login
    build:
      context: ./backend/services/sqlite/sqlite-login
      dockerfile: Dockerfile
    volumes:
      - ./backend/services/sqlite/sqlite-login:/src
      - sqlite-login_data:/data
    environment:
      - ${LOGIN_PORT}=${LOGIN_PORT}
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
    networks:
      - service-net

# ------------------------- VOLUMES ------------------------ #

volumes:
  redis_data:
  node-oauth_data:
  node-game_data:
  sqlite-login_data:

# ------------------------- NETWORK ------------------------ #

networks:
  public-net:
    name: public-net
    driver: bridge
  service-net:
    name: service-net
    driver: bridge
